### ISSUE TITLE
Working on something similar

### ISSUE THREAD

**Issue by axe312ger** [blocks/blocks#2]
See https://github.com/axe312ger/mdx-live-editor

Maybe we can join forces? :)

**Comment by axe312ger** [comment]
Wanted to give more context, so, thats what I did:

* Started to transform https://github.com/sparksuite/simplemde-markdown-editor, which is no more maintained to I found https://github.com/Ionaru/easy-markdown-editor which is better maintained.
* Anyways, turned out non-react rendering is not really helpful, since I want dynamic MDX components, not just static ones. Outcome is here: https://axe312ger.github.io/mdx-live-editor/
* Started working on my own implementation, played around with https://codemirror.net & https://ace.c9.io/ and my own custom rendering. Outcome is here: https://axe312ger.github.io/mdx-live-editor/custom-editor/

Biggest issues I runned into:

* Proper detection if current pointer/cursor is inside a MDX component/block or just regular markdown
* Scrollsync on percentages is not really useful. My approach was to detect the current element, inject a hidden `<a id="scrollhere" />` at the current position and scroll there

I think the key to get a MDX editor properly working is to parse the AST of the MDX, and build a preview and the actual editor lines based on that AST. That way toolbar buttons can properly toggle on/off of formatting or even open a configuration form/window for the component the user is currently editing.

Hope this helps,
Let me know :)

Benedikt

**Comment by axe312ger** [comment]
Here is a screen capture of how it feels like when editing diagrams live in your MDX. I am stunned, if we get this running properly, its a huge step for editor experience with MDX

![mdx-live-editor-smaller](https://user-images.githubusercontent.com/1737026/56452487-7786af80-635b-11e9-8cb1-9cd40c13fdba.gif)

**Comment by johno** [comment]
This is super rad @axe312ger!

We'd definitely love to join forces. Our current focus for the alpha release is more based around a WYSIWYG experience, which my [tweet briefly outlines](https://mobile.twitter.com/4lpine/status/1119307881709309952).

But, the goals of this project are super ambitious and we'd love to support a live editor (like what you're building), adding dynamic component support, theme editing, and an awesome standard library of stuff like image grids, diagrams, etc.

#### A bit about our current architecture

Our current proof of concept is using [Slate](https://slatejs.org) and custom serialization so that we can render components that can progressively disclose more knobs and dials since we want to abstract MDX away for those that don't want to write Markdown/JSX (think Dropbox Paper, Notion).

In addition to abstracting away MDX, we also want an editing mode that exposes MDX syntax (precisely what you're building) so there's an amazing fit there.

---

I'd be curious to know if this aligns with your goals with `mdx-live-editor`? If there's common ground it'd be amazing to contribute to the same project so that we can make the best possible library. If it aligns, we'd love to add you as a contributor and start figuring out how we can join forces.

**Comment by axe312ger** [comment]
Hey @johno,

this absolutely aligns with my goals, I mostly just want such an editor to happen. What I see and read is amazing, keep this going, I am happy to help.

I had slate already on my table, but decided that wysiwyg might get super tricky, especially with complex components. First focus was to hack some prototype to see how it feels to use it.

Some stuff that showed up while working on it:

## embedding

As one of the main goals I'd ensure that this library is easily embeddable into any (headless) CMS that supports custom UI extenstions.

## custom components

standard components are neat, but for real projects, you'll need custom ones. These need to be easily embeddable

## (Technically) complex components

These showed up more quickly as expected, especially building forms for authors might be nasty here

### Nested components

Authors and designers like to get crazy nowadays. Design must be selectively configurable, images and colors have to break the grid, background images must be assignable when needed. This needs a lot of custom css & html, but is pretty easy to expose as MDX component 😻  

```markdown
<Sections>
<Section>

# Amazing headline

<Grid minWidth="500px" centered>

Column 1

Column 2

</Grid>
</Section>
<Section colorScheme="dark">
<Video youtubeId="oHg5SJYRHA0" />
</Section>
</Sections>
```


### Composable components

 I came up with composable components to give editors the full MDX power when nessessary. See this example for a carousel with MDX slides:

```markdown
<Carousel>
<CarouselNavigation>

Navigation Item 1

Navigation Item 2

Navigation Item 3

</CarouselNavigation>
<CarouselSlides>
<CarouselSlide>

First carousel slide. Linked with first navigation item.

</CarouselSlide>
...
</CarouselSlides>
```

For the navigation, I could just have used a comma separated string or an array prop. 🤔


### Multi line attributes

Can get tricky to edit and also syntax highlight. Like the diagram from the demo above:

```markdown
<Diagram diagram={`
graph LR;
    Markdown-->MDX;
    react[Custom React Components]-->MDX;
    MDX-.-Renderer[MDX runtime];
    CodeMirror-.MDX code.->Renderer;
    Renderer-->Preview[Live Preview];
`}/>
```


### Media components

Here will WYSIWYG definitely win in UX/EX, as media is always a reference to somewhere. Either a URI, some database or API. It must be possible to reuse the given image/video/whatevery component for the developer and assign their own data input & selection form.

Further: Images sometimes need to be linked, centered, have a fixed or fluid with. This all need to be configurable if desired.

```markdown
<Image id="1234abcd" centered maxWidth="200px" />
```

## Split view & scroll sync

As mentioned creating proper scroll sync can be tricky, but I am optimistic that slate will help here a lot.

## Some other stuff I'd love to see

* autocomplete for tags!
* simple linting. forgotten closing tags can be nightmare
* automatic formatting? prettier? <3

---

Just wanted to share my findings,
will have a closer look as soon I get the demo running (#25)

Best,
Benedikt

**Comment by johno** [comment]
Wonderful, I've invited you to the Blocks org @axe312ger. ❤️ 🎉 

> but decided that wysiwyg might get super tricky, especially with complex components

Ha, yep 😆 

> As one of the main goals I'd ensure that this library is easily embeddable into any (headless) CMS that supports custom UI extenstions.

💯 This is def our primary goal as well. Ideally this can be a building block for CMSes/products with a rich API for customization and extending.

> standard components are neat, but for real projects, you'll need custom ones. These need to be easily embeddable

Yeah, we have that _partially_ worked out with jsx/jsx-void node types in the WYSIWYG but there's a lot more work to go there. Though, right now, components that are passed into the editor automatically show up in the "Insert Block" dropdown 🕺. We still need a lot of work going into handling custom component embedding inside other custom components. That will be quite a rabbit hole.

This is exactly what you bring up in complex/nested/composable components. I think, for the alpha release of the WYSIWYG side we might ignore this and maybe add it as something to address for beta/v1 since it will be tricky.

> Split view & scroll sync

💯 

> Some other stuff I'd love to see

😻 

---

If you're interested, something where it looks you could make a super valuable impact is building out the raw MDX piece in `@blocks/editor`. In addition to the WYSIWYG we want to expose a "code" mode where an MDX code editor is exposed in place of the slate WYSIWYG.

For the preview piece, we _might_ even be able to render the WYSIWYG side in readOnly mode or something which would allow us to keep consistency in rendering.

Would you be interested in taking this on @axe312ger? If so, feel free to open up an issue and assign yourself. I'll also work on adding more issues of features and such we'd like to add. You're welcome to take on any of them that you'd like.

💟 Looking forward to collaborating.
